title: "Mete Ismayilzada"
url: "https://mete.is"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://mete.is"
footer_text: "Fin"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: ""
 - name: "CV"
   link: "CV.pdf"
